# Generated by Django 6.0.6 on 2026-07-03 22:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('DENEGADO', 'Denegado')], default='APROBADO', max_length=10)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('tipo_acceso', models.CharField(default='entrada', max_length=10)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.estudiante')),
            ],
            options={
                'verbose_name_plural': 'Accesos',
            },
        ),
    ]
